version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: